-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 14:01:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flordeliz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flordeliz` ;

-- -----------------------------------------------------
-- Schema flordeliz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flordeliz` DEFAULT CHARACTER SET latin1 ;
USE `flordeliz` ;

-- -----------------------------------------------------
-- Table `flordeliz`.`calcado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flordeliz`.`calcado` ;

CREATE TABLE IF NOT EXISTS `flordeliz`.`calcado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `colecao` VARCHAR(30) NOT NULL,
  `tamMax` INT(11) NOT NULL,
  `tamMin` INT(11) NOT NULL,
  `precoCusto` DOUBLE NOT NULL,
  `cor` VARCHAR(20) NOT NULL,
  `valorVenda` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flordeliz`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flordeliz`.`cliente` ;

CREATE TABLE IF NOT EXISTS `flordeliz`.`cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(50) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `loja` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flordeliz`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flordeliz`.`pedido` ;

CREATE TABLE IF NOT EXISTS `flordeliz`.`pedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idCliente` INT(11) NOT NULL,
  `valorTotal` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `flordeliz`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flordeliz`.`itempedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flordeliz`.`itempedido` ;

CREATE TABLE IF NOT EXISTS `flordeliz`.`itempedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idpedido` INT(11) NOT NULL,
  `idproduto` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `tamano` INT(11) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_item`
    FOREIGN KEY (`idproduto`)
    REFERENCES `flordeliz`.`calcado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `flordeliz`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flordeliz`.`lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flordeliz`.`lote` ;

CREATE TABLE IF NOT EXISTS `flordeliz`.`lote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigoProducao` VARCHAR(20) NOT NULL,
  `dtProducao` DATE NULL DEFAULT NULL,
  `idcalcado` INT(11) NOT NULL,
  `tamanhoCalcado` INT(11) NOT NULL,
  `quantidadeProduzido` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_calcado`
    FOREIGN KEY (`idcalcado`)
    REFERENCES `flordeliz`.`calcado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
